name: civitai model

on:
  workflow_dispatch:
  schedule:
    - cron: "00 12 * * *"

jobs:
  google_search:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install required Python dependencies
      run: |
        pip install DataRecorder tqdm aiohttp pandas python-dotenv httpx cloudflare requests waybackpy cdx_toolkit bs4 lxml

    - name: Run the Google search parser script
      env:
        CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        CLOUDFLARE_D1_DATABASE_ID: ${{ secrets.CLOUDFLARE_D1_DATABASE_ID }}
      run: |
        python civitai.py

    # - name: Commit the results to the repository if there's a change
      # run: |
        # git config --global user.name "GitHub Action"
        # git config --global user.email "action@github.com"
      
        # git add -A
        # git commit -m "Add new Google search results"
        # git push
