name: update topios100 daily

on:
  workflow_dispatch:  # Trigger manually
  schedule:
    - cron: "00 12 * * *"

jobs:
  scrape-app-store:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'  # Ensure your required version is used

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install aiohttp aiohttp_socks DataRecorder pandas DrissionPage python-dotenv 

      - name: Run scraper and save results
        run: |
          python update-daily-top100.py
        env:
          RESULT_FOLDER: ./result  # Adjust if necessary
          OUTPUT_FOLDER: ./output

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        
        with:
          tag_name: app-store-data-${{ github.run_number }}
          release_name: App Store Data
          draft: false
          prerelease: false
          body: "Results of App Store data processing."

      - name: Upload artifacts to release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./result/top-100-app-*.csv
          asset_name: top-100-app.csv
          asset_content_type: text/csv
